"""
month-2-finance/schemas.py
--------------------------
Pydantic schemas for financial transaction ingestion, deterministic risk assessment,
automated order execution, and audit logging.
"""

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional
from pydantic import BaseModel, Field, SecretStr


# ============================================================================
# Enums
# ============================================================================

class TransactionType(str, Enum):
    WIRE_TRANSFER = "WIRE_TRANSFER"
    ACH_PAYMENT = "ACH_PAYMENT"
    CARD_PURCHASE = "CARD_PURCHASE"
    CRYPTO_SWAP = "CRYPTO_SWAP"
    SECURITIES_ORDER = "SECURITIES_ORDER"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FinancialAction(str, Enum):
    APPROVE = "APPROVE"
    MONITOR = "MONITOR"
    FLAG_FOR_REVIEW = "FLAG_FOR_REVIEW"
    AUTO_REJECT = "AUTO_REJECT"
    FREEZE_ACCOUNT = "FREEZE_ACCOUNT"


class ExecutionStatus(str, Enum):
    PENDING = "PENDING"
    EXECUTED = "EXECUTED"
    REJECTED = "REJECTED"
    HELD_FOR_APPROVAL = "HELD_FOR_APPROVAL"


# ============================================================================
# Ingestion Models
# ============================================================================

class FinancialTransaction(BaseModel):
    """Incoming transaction event to be evaluated for risk and compliance."""
    transaction_id: str = Field(..., description="Unique transaction ID (e.g., TXN-9901)")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="UTC timestamp of transaction initiation")
    account_id: str = Field(..., description="Source account or portfolio ID")
    counterparty_id: str = Field(..., description="Destination or counterparty identifier")
    transaction_type: TransactionType = Field(..., description="Type of financial operation")
    amount: float = Field(..., gt=0, description="Monetary value in USD (must be positive)")
    currency: str = Field(default="USD", description="3-letter ISO currency code")
    source_country: str = Field(..., description="ISO 2-letter country code of origin")
    destination_country: str = Field(..., description="ISO 2-letter country code of destination")
    metadata: Dict[str, str] = Field(default_factory=dict, description="Contextual payload (IP address, device hash, merchant category, etc.)")


# ============================================================================
# Risk Assessment Models
# ============================================================================

class RiskRuleTrigger(BaseModel):
    """Specific compliance or quantitative risk rule triggered during evaluation."""
    rule_id: str = Field(..., description="Unique rule code (e.g., AML-001, HYPER_VELOCITY)")
    rule_name: str = Field(..., description="Human-readable rule title")
    severity: RiskLevel = Field(..., description="Severity attributed to this specific trigger")
    description: str = Field(..., description="Explanation of why this rule was triggered")


class RiskAssessmentReport(BaseModel):
    """Output generated by the Risk Scoring Agent for an incoming transaction."""
    transaction_id: str = Field(..., description="ID of the evaluated transaction")
    risk_score: float = Field(..., ge=0.0, le=100.0, description="Quantitative risk score from 0.0 (safe) to 100.0 (extreme risk)")
    risk_level: RiskLevel = Field(..., description="Categorical risk classification")
    recommended_action: FinancialAction = Field(..., description="Recommended action based on threshold policy")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Agent confidence score (0.0 - 1.0)")
    triggered_rules: List[RiskRuleTrigger] = Field(default_factory=list, description="List of compliance/risk rules triggered")
    reasoning_trace: List[str] = Field(..., description="Step-by-step audit steps leading to the risk evaluation")


# ============================================================================
# Execution & Order Models
# ============================================================================

class MitigationStep(BaseModel):
    """Actionable execution or remediation step for a flagged transaction."""
    step_number: int = Field(..., ge=1, description="Sequential step index")
    action_item: str = Field(..., description="Detailed description of the action")
    requires_human_approval: bool = Field(..., description="True if step involves blocking accounts, police reports, or manual overrides")
    assigned_role: str = Field(default="SYSTEM", description="Role responsible for executing step (e.g., SYSTEM, COMPLIANCE_OFFICER, MLRO)")


class ExecutionOrder(BaseModel):
    """Order generated to execute, route, or block a evaluated financial transaction."""
    order_id: str = Field(..., description="Unique execution order ID")
    transaction_id: str = Field(..., description="Associated transaction ID")
    action: FinancialAction = Field(..., description="Final action to execute")
    status: ExecutionStatus = Field(default=ExecutionStatus.PENDING, description="Current execution state")
    mitigation_plan: List[MitigationStep] = Field(..., description="Sequence of execution and compliance steps")
    approved_by: Optional[str] = Field(None, description="Identifier of human approver if human approval was required")
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ============================================================================
# Audit & Ledger Logs
# ============================================================================

class AuditLedgerEntry(BaseModel):
    """Immutable audit entry written to the event ledger for compliance auditing."""
    log_id: str = Field(..., description="Unique ledger log entry ID")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    transaction_id: str = Field(..., description="Target transaction ID")
    account_id: str = Field(..., description="Associated account ID")
    event_type: str = Field(..., description="Type of event recorded (e.g., RISK_EVALUATED, ORDER_EXECUTED, HELD_FOR_COMPLIANCE)")
    payload: Dict[str, str] = Field(..., description="Key-value snapshot of execution state")